# Generated by Django 5.0.2 on 2024-04-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_tutor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='is_active',
        ),
    ]
