# Generated by Django 5.0.2 on 2024-03-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_subject_organization_subject_tutors_ticket_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
    ]
