# Generated by Django 5.0.2 on 2024-03-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketingcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketingcode',
            options={'verbose_name': 'Ticketing Code', 'verbose_name_plural': 'Ticketing Code'},
        ),
    ]
