# Generated by Django 5.0.2 on 2024-04-01 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketingcode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='session_time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The end time of the session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The start time of the session'),
        ),
    ]
