# Generated by Django 5.0.2 on 2024-04-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_tutororganization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorOrganization',
        ),
    ]
