# Generated by Django 5.0.2 on 2024-04-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_tutor_is_active'),
        ('tickets', '0010_delete_tutororganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.organization')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tutors',
            field=models.ManyToManyField(related_name='organizations', through='tickets.OrganizationTutor', to='Users.tutor'),
        ),
    ]
